<?php

namespace AppBundle\Repository;

/**
 * CleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CleRepository extends \Doctrine\ORM\EntityRepository
{
}
