<?php

namespace AppBundle\Repository;

/**
 * EmpruntRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpruntRepository extends \Doctrine\ORM\EntityRepository
{
    public function deleteAllEmprunt()
    {
        $qb = $this->createQueryBuilder('e');
        $qb->delete()
            ->getQuery()
            ->execute();
    }
}
