<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EmpruntRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpruntRepository extends \Doctrine\ORM\EntityRepository
{
    public function deleteAllEmprunt()
    {
        $qb = $this->createQueryBuilder('e');
        $qb->delete()
            ->getQuery()
            ->execute();
    }

    public function insertEmprunt(int $idVehicule, string $commentaireEmprunt)
    {
        $queryBuilder = $this->createQueryBuilder('e');
        //$query = $this->create('INSERT INTO dbo.emprunt (Vehicule_id_id, commentaire) VALUES (?, ?)');
        //$query->setParameter($idVehicule, $commentaireEmprunt);
        //$query->execute();
        $queryBuilder->add('emprunt')->values(['vehicule_id_id' => '?', 'commentaire' => '?'])->setParameter(0, $idVehicule)->setParameter(1, $commentaireEmprunt);
        return $queryBuilder->execute();
    }
}
