<?php

namespace AppBundle\Repository;

/**
 * Emprunt_PersonneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Emprunt_PersonneRepository extends \Doctrine\ORM\EntityRepository
{
}
