<?php

namespace AppBundle\Repository;

/**
 * Lieu_empruntRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Lieu_empruntRepository extends \Doctrine\ORM\EntityRepository
{
}
