<?php

namespace AppBundle\Repository;

/**
 * Localisation_CleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Localisation_CleRepository extends \Doctrine\ORM\EntityRepository
{
    public function deleteAllCleRepository()
    {
        $qb = $this->createQueryBuilder('l');
        $qb->delete()
            ->getQuery()
            ->execute();
    }
}
