<?php

namespace AppBundle\Repository;

/**
 * PersonneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonneRepository extends \Doctrine\ORM\EntityRepository
{
    public function deleteAllPersonne()
    {
        $qb = $this->createQueryBuilder('p');
        $qb->delete()
            ->getQuery()
            ->execute();
    }
}
