<?php

namespace AppBundle\Repository;

/**
 * RdvRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RdvRepository extends \Doctrine\ORM\EntityRepository
{
    public function deleteAllRdv()
    {
        $qb = $this->createQueryBuilder('r');
        $qb->delete()
            ->getQuery()
            ->execute();
    }
}
