app:
    resource: '@AppBundle/Controller/'
    type: annotation

gestion_form_ajout_categorie:
    path:     /demande/demande/
    defaults: { _controller: AppBundle:Demande:formAjoutCateg }
    requirements:
        _method: GET